# Generated by Django 5.2.17 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('jurisdiccion', models.CharField(db_index=True, max_length=8)),
                ('clase', models.CharField(max_length=24)),
                ('rango_normativo', models.CharField(max_length=80)),
                ('cita', models.TextField()),
                ('pinpoint', models.CharField(blank=True, max_length=120)),
                ('tipo_localizador', models.CharField(max_length=16)),
                ('localizador', models.CharField(max_length=300)),
                ('url_oficial', models.URLField(blank=True, max_length=400)),
                ('confianza_verificacion', models.CharField(blank=True, max_length=32, null=True)),
                ('verificada_el', models.DateField()),
                ('ruta_fichero', models.CharField(max_length=300, unique=True)),
                ('hash_fichero', models.CharField(max_length=64)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fichas',
                'ordering': ['jurisdiccion', 'id'],
            },
        ),
    ]
