# Generated by Django 5.2.17 on 2026-08-16 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_index=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('engine_version', models.CharField(max_length=16)),
                ('dataset_version', models.CharField(max_length=16)),
                ('has_ai_explanation', models.BooleanField(default=False)),
                ('payload', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'casos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='casos_usuario_f16ec4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('usuario', 'titulo'), name='titulo_unico_por_usuario_entre_casos_vivos')],
            },
        ),
    ]
