# Generated by Django 5.2.17 on 2026-08-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoContrastado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=160)),
                ('payload', models.JSONField()),
                ('comentario_curador', models.TextField()),
                ('publicado', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('caso_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis.caso')),
                ('curado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'casos_contrastados',
                'ordering': ['-creado_el'],
            },
        ),
    ]
