# Generated by Django 5.2.17 on 2026-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(max_length=300)),
                ('cuerpo', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('fichas', models.ManyToManyField(blank=True, related_name='unidades', to='corpus.ficha')),
            ],
            options={
                'db_table': 'unidades_estudio',
                'ordering': ['orden', 'titulo'],
                'indexes': [models.Index(fields=['publicada', 'orden'], name='unidades_es_publica_b57e38_idx')],
            },
        ),
    ]
