# Generated by Django 5.2.17 on 2026-08-17 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_el', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('proposito', models.CharField(db_index=True, max_length=32)),
                ('modelo', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=40)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_salida', models.PositiveIntegerField(default=0)),
                ('tokens_cache_escritura', models.PositiveIntegerField(default=0)),
                ('tokens_cache_lectura', models.PositiveIntegerField(default=0)),
                ('coste_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latencia_ms', models.PositiveIntegerField()),
                ('razon_finalizacion', models.CharField(blank=True, max_length=32)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('intento', models.PositiveSmallIntegerField()),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis.caso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llamadas_llm',
                'ordering': ['-creada_el'],
                'indexes': [models.Index(fields=['usuario', 'creada_el'], name='llamadas_ll_usuario_a6d976_idx')],
            },
        ),
    ]
