# Generated by Django 5.2.17 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoEvaluacion',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('entrada', models.JSONField()),
                ('propiedades_esperadas', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'casos_evaluacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutada_el', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sha_commit', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=40)),
                ('casos_totales', models.PositiveIntegerField()),
                ('casos_acertados', models.PositiveIntegerField()),
                ('tasa_acierto', models.FloatField()),
                ('coste_total_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latencia_p50_ms', models.PositiveIntegerField()),
                ('latencia_p95_ms', models.PositiveIntegerField()),
                ('es_linea_base', models.BooleanField(default=False)),
                ('detalle', models.JSONField()),
            ],
            options={
                'db_table': 'ejecuciones_evaluacion',
                'ordering': ['-ejecutada_el'],
            },
        ),
    ]
